#include "DistilBERT/IR/DistilBERTDialect.h.inc"
#include "mlir/IR/DialectImplementation.h"

using namespace mlir;
using namespace mlir::distilbert;

//===----------------------------------------------------------------------===//
// DistilBERT dialect.
//===----------------------------------------------------------------------===//

void DistilBERTDialect::initialize() {
  addOperations<
#define GET_OP_LIST
#include "DistilBERT/IR/DistilBERTOps.cpp.inc"
      >();
}

// Dialect definition file generated by TableGen
#include "DistilBERT/IR/DistilBERTDialect.cpp.inc"
